title: The AVR-Sandbox Project
description: Dig deeper into the avr world and discover every single bit in embedded engineering and IoT.
show_downloads: true
google_analytics: true
theme: jekyll-theme-slate
avatar: https://user-images.githubusercontent.com/60224159/178119492-91d3cc70-a88f-4b9a-94a0-ca7b68b1d861.png
